lorenzoProject/lorenzoProject/urls.py
from django.contrib import admin  
from django.urls import path  
from magazzino import views  
urlpatterns = [  
	path('admin/', admin.site.urls),  
	path('maga', views.maga),  
	path('show',views.show),  
	path('edit/<int:id>', views.edit),  
	path('update/<int:id>', views.update),  
	path('delete/<int:id>', views.destroy),  
]  

lorenzoProject/magazzino/models.py
from django.db import models
from django import forms

class Magazzino(models.Model):
        eid     = models.CharField(max_length=20)
        subkey  = models.CharField(max_length=20)
        ename   = models.CharField(max_length=50)
        quantity = models.IntegerField()
        code_maker  = models.CharField(max_length=20)
        code_vendor  = models.CharField(max_length=20)
        edescription = models.TextField( blank=True )
        progetto  = models.CharField(max_length=20)
        class Meta:
              db_table = "magazzino"

lorenzoProject/magazzino/forms.py
from django import forms  
from magazzino.models import Magazzino  

class MagazzinoForm(forms.ModelForm):  
	class Meta:  
		model = Magazzino  
		fields = "__all__"  

lorenzoProject/magazzino/views.py
from django.shortcuts import render, redirect  
from magazzino.forms import MagazzinoForm  
from magazzino.models import Magazzino  

# Create your views here.  
def maga(request):  
	if request.method == "POST":  
		form = MagazzinoForm(request.POST)  
		if form.is_valid():  
			try:  
				form.save()  
				return redirect('/show')  
			except:  
				pass  
	else:  
		form = MagazzinoForm()  
	return render(request,'index.html',{'form':form})  

def show(request):  
	magazzinos = Magazzino.objects.all()  
	return render(request,"show.html",{'magazzinos':magazzinos})  

def edit(request, id):  
	magazzino = Magazzino.objects.get(id=id)  
	return render(request,'edit.html', {'magazzino':magazzino})  

def update(request, id):  
	magazzino = Magazzino.objects.get(id=id)  
	form = MagazzinoForm(request.POST, instance = magazzino)  
	if form.is_valid():  
		form.save()  
		return redirect("/show")  
	return render(request, 'edit.html', {'magazzino': magazzino})  

# old destroy def - doesn't ask for a confirmation
#def destroy(request, id):  
	#magazzino = Magazzino.objects.get(id=id)  
	#magazzino.delete()  
	#return redirect("/show")  
	
# new destroy def -  ask for a confirmation	!!! ( confirm_delete.html extend edit.html )
def destroy(request, id, template_name='confirm_delete.html'):  
    magazzino = Magazzino.objects.get(id=id)  
    form = MagazzinoForm(request.POST, instance = magazzino)  
    if request.method=='POST':
	    magazzino.delete()
	    return redirect("/show")
    return render(request, 'confirm_delete.html', {'magazzino': magazzino})  

  

lorenzoProject/magazzino/templates/confirm_delete.html
{% extends 'edit.html' %}
{% block content %}
<div class="container">
    <div class="row"></div>
    <br />
    <div class="row">
        <div class="col-md-2 col-xs-2 col-sm-2"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning">
                        Are you sure you want to delete {{ object }}?
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i> DELETE !
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

lorenzoProject/magazzino/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<title>magazzino Project - edit</title>  
   
	{% load static %}  
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
	<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/> 
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>  
<body>  
	
<form method="POST" class="post-form" action="/update/{{magazzino.id}}">  
		{% csrf_token %}  
<div class="container bg-light"><br>
  
  <div class="form-group row">  
	 <label class="col-sm-1 col-form-label"></label>  
	 <div class="col-sm-4">  
	 <h3>Update Record</h3>  
    </div>  
  </div>  

  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Id:</label>  
	<div class="col-sm-4">  
		<input class="form-control"  type="text" name="eid" id="id_eid" required maxlength="20" value="{{ magazzino.eid }}"/>  
	</div>  
  </div> 
   
  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Subkey:</label>  
	<div class="col-sm-4">  
		<input class="form-control"  type="text" name="subkey" id="id_subkey" required maxlength="20" value="{{ magazzino.subkey }}"/>  
	</div>  
  </div> 

  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Name:</label>  
	<div class="col-sm-4">  
		<input class="form-control"  type="text" name="ename" id="id_ename" required maxlength="60" value="{{ magazzino.ename }}"/>  
	</div>  
  </div> 

  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Quantity:</label>  
	<div class="col-sm-4">  
		<input class="form-control"  type="number" name="quantity" id="id_quantity" required maxlength="100" value="{{ magazzino.quantity }}" />  
	</div>  
  </div>  
  
  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Code Maker:</label>  
	<div class="col-sm-4">  
		<input class="form-control"  type="text" name="code_maker" id="id_code_maker" required maxlength="100" value="{{ magazzino.code_maker }}" />  
	</div>  
  </div>  

  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Code Vendor:</label>  
	<div class="col-sm-4">  
		<input class="form-control"  type="text" name="code_vendor" id="id_code_vendor" required maxlength="100" value="{{ magazzino.code_vendor }}" />  
	</div>  
  </div>  
	
  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Description:</label>  
	<div class="col-sm-4">  
		 <textarea class="form-control" name="edescription" id="id_edescription" rows="3"  >{{ magazzino.edescription }}</textarea> 
		 <!-- <input type="text" name="edescription" id="id_edescription" required maxlength="500" value="{{ magazzino.edescription }}" />  -->
	</div>  
  </div>  
	
	
  <div class="form-group row">  
	<label class="col-sm-2 col-form-label">Progetto:</label>  
	<div class="col-sm-4">  
		 <!-- <textarea class="form-control" name="edescription" id="id_edescription" rows="3"  >{{ magazzino.progetto }}</textarea> -->
		 <input class="form-control" type="text" name="progetto" id="id_progetto" required maxlength="20" value="{{ magazzino.progetto }}" /> 
	</div>  
  </div>  
	
	
  <div class="form-group row">  
	<label class="col-sm-1 col-form-label"></label>  
	<div class="col-sm-4">  
	<button type="submit" class="btn btn-primary">Update</button> 
	<a href="/show" class="btn btn-success">Back</a>  
	</div>  
  </div>  
</div>  
</form>  

{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</body>  
</html>  

lorenzoProject/magazzino/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<title>magazzino Project - index</title>  

	{% load static %}  
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
	<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>  
<body>  
<form method="POST" class="post-form" action="/maga">  
		{% csrf_token %}  
	
  <div class="container bg-light"><br>  
    <div class="form-group">  
	<label class="col-form-label"></label>  
	  <div class="">  
	    <h3>Add New Record</h3>  
	  </div>  
    </div>  

  <div class="form-group">  
	<label class="form-group">Id:</label>  
	<div class="form-group">  
	  {{ form.eid }}  
        </div>  
  </div>  

  <div class="form-group">  
	<label class="form-group">Subkey:</label>  
	<div class="form-group">  
	  {{ form.subkey }}  
        </div>  
  </div>  

  <div class="form-group">  
	<label class="form-group">Name:</label>  
	<div class="form-group">  
	  {{ form.ename }}  
        </div>  
  </div>  





  <div class="form-group">  
	<label class="form-group">Quantity:</label>  
	<div class="form-group">  
	  {{ form.quantity }}  
	</div>  
  </div>  
	<div class="form-group">  
	<label class="form-group">Code Maker:</label>  
	<div class="form-group">  
	  {{ form.code_maker }}  
	</div>  
  </div>  
      <div class="form-group">
        <label class="form-group">Code Vendor:</label>
        <div class="form-group">
          {{ form.code_vendor }}
        </div>
  </div>

	<div class="form-group">  
	<label class="form-group">Description:</label>  
	<div class="form-group">  
	  {{ form.edescription }}  
	</div>  
  </div>  


	<div class="form-group">  
	<label class="form-group">Progetto:</label>  
	<div class="form-group">  
	  {{ form.progetto }}  
	</div>  
  </div>  


	<div class="form-group">  
	<label class="form-group"></label>  
	<div class="form-group">  
	<button type="submit" class="btn btn-primary">Submit</button>  
	<a href="/show" class="btn btn-success">Back</a> 
	</div>  
  </div>  
</div>  
</form>  
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</body>  
</html>  

lorenzoProject/magazzino/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<title>magazzino Project - show</title>  
	 
	{% load static %}  
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
	<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<!-- Icons -->
	<script src="https://kit.fontawesome.com/6c50d63416.js" crossorigin="anonymous"></script>
	<!-- DataTables -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
	<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
	
</head>  
<body>  
	
	
<div class="container bg-dark">		
	<div class="row">
		<div class="col-sm">
			<h4 class="text-warning"><a href="https://github.com/roitnedurp/Magazzino" target=”_blank”> Magazzino standalone v. 0.0.3 </a></h4>
		</div> 
		<div class="col-sm">
			<p class="text-warning"> <a href="/maga" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add New Record</a> </p>
		</div> 
	</div>
</div>
	
	
<div class="container bg-light">	
<table id="sortTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">	
<!--
<table class="table table-striped table-bordered table-sm">  
-->
	<thead class="thead-dark">  
	<tr>  
		<th>ID</th>  
		<th>Sub</subkey>  
		<th>Name</th>  
		<th>Quantity</th>
		<th>Code Maker</th>  
		<th>Code Vendor</th>  
		<th>Description</th>
		<th>Progetto</th>
		<th>Actions</th>  
	</tr>  
	</thead>  
	<tbody>  
{% for magazzino in magazzinos %}  
	<tr>  
		<td>{{ magazzino.eid }}</td>  
		<td>{{ magazzino.subkey }}</td>  
		<td>{{ magazzino.ename }}</td>
		<td>{{ magazzino.quantity }}</td>  
		<td>{{ magazzino.code_maker }}</td>  
		<td>{{ magazzino.code_vendor }}</td>  
		<td>{{ magazzino.edescription }}</td>
		<td>{{ magazzino.progetto }}</td>  
  
		<td>  
			<a href="/edit/{{ magazzino.id }}"><i class="fas fa-pencil-alt"></i> Edit</span></a>  <br>
			<a href="/delete/{{ magazzino.id }}"><i class="fas fa-trash-alt"></i> Delete</span></a>  
		</td>  
	</tr>  
{% endfor %}  
	</tbody>  
</table>  
<br>  
<br>  

<!--
<script>
$('#sortTable').DataTable();
</script>
-->


<script>
	//$(document).ready(function() {
	    $('#sortTable').DataTable( {
	        "lengthMenu": [[10, 25, 50, -1], [100, 25, 50, "All"]]
	    } );
	//} );
</script>


 
</div>
{% block content %}
{% endblock %}
 
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script> 
</body>  
</html>  